# Generated by Django 5.1.1 on 2024-09-11 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_author_description_author_image_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateTimeField(default=datetime.timedelta(days=30)),
        ),
    ]
