# Generated by Django 5.1.1 on 2024-09-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_alter_plan_end_date_alter_plan_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(choices=[('Quarterly Plan', 'Quarterly Plan'), ('Half-yearly Plan', 'Half-yearly Plan'), ('Annual Plan', 'Annual Plan')], max_length=20),
        ),
    ]
