# Generated by Django 5.1.1 on 2024-09-12 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_alter_plan_plan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateField(auto_now_add=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('rental_status', models.CharField(choices=[('rented', 'Rented'), ('returned', 'Returned')], default='rented', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateField(auto_now_add=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('rental_status', models.CharField(choices=[('rented', 'Rented'), ('returned', 'Returned')], default='rented', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
